### ISSUE TITLE
[BUG]: The WeMod launcher fails with errno 25

### ISSUE THREAD

**Issue by j3nesis87** [DeckCheatz/wemod-launcher#130]
### Describe the bug

When trying to 'Download' the launcher, I get "[Errno 25] Inappropriate ioctl for device" in the log.
My OS: Mint 22

### Steps to reproduce the behavior

1. Install WeMod-Launcher as per instructions
2. Add launch option to Steam game
3. Play Steam game
4. Launcher comes up with the 'Download or Build?' option
5. Launcher errors out when using Download

### Expected behavior

Launcher to download

### Logs

[wemod.log](https://github.com/user-attachments/files/17317006/wemod.log)

### System Information

OS: Linux Mint 22
Proton: GE-Proton-9.15

**Comment by marvin1099** [comment]
Was there a download window after you clicked on download?
It should say somting like:
downloading ... 1/34325 (the numbers are random yours will differ).
Or is the error directly after you click download.

A possible solution may be to delete this file:
/home/jenny/wemod-launcher/.cache/wemod_prefix9.1.zip 

You can try that, se if that works.

**Comment by marvin1099** [comment]
Actually i think i just fixed this in commit [ 743189a29c259b3010120625a17b46d2cc5312af](https://github.com/DeckCheatz/wemod-launcher/commit/743189a29c259b3010120625a17b46d2cc5312af).
Retry, it should auto update and run fine afterwards
