### ISSUE TITLE
[BUG]: The WeMod launcher won`t continue after x

### ISSUE THREAD

**Issue by lolwulf2** [DeckCheatz/wemod-launcher#133]
### Describe the problem

i have been trying to get wemod to work with command and conquer 3 tiberium wars, everything seemd to be going well how ever after adding int the custom start up command "/home/$USER/wemod-launcher/wemod %command%" adding in the correct user under $user. the game refuses to even start when i click play there is a breif peried where steam attempts to launch but then stops again

### Steps that will result in the problem

add custom launch command "/home/angel/wemod-launcher/wemod %command%"  and the game nor wemod refuses to start

### Expected results

the game should start, and wemod should open

### Logs

no logs were ever produced even when attempting the full custom launch option WEMOD_LOG=/home/angel/wemod-launcher/wemod.log /home/angel/wemod-launcher/wemod %command%

### System Information

zorin OS 17.2 core
ge-proton 9.9 and regular proton

**Comment by lolwulf2** [comment]
forgot to add the game launched normally and works just fine without the custom launch command

**Comment by marvin1099** [comment]
if there is no log that means, 
the file wemod (the wemod-launcher) was not found (that is the most plausible solution),
dobble check if the wemod launcher is actually in the path /home/angel/wemod-launcher/wemod
and if it is you are probably using the steam flatpak,
if you are not unsing the flatpak say so (this is important).

If you are runnig the flatpak,
kepp in mind the support for the steam flatpak is not great,
but if you want to try to make it work with the flatpak follow this guide
https://github.com/DeckCheatz/wemod-launcher/wiki/Steam-Flatpak-Usage
But consider using the regular steam version if you can.

If you are running the regular version of steam we need to run some more test,
first close steam, then run the command 'steam' in a terminal
After that any issues will be printed in the terminal,
so try to start the game and after it failed send over the output of the teminal.

**Comment by calvyb** [comment]
name error sys is not defined did you forgetto import sys.

after a recent system update my terminal kicks out something like this. wont even start anymore..  will paste exact logs when home.

**Comment by marvin1099** [comment]
I think i just fixed it, retry please.

**Comment by marvin1099** [comment]
Actually you probably have to use:
```
cd /home/$USER/wemod-launcher
git reset --hard origin
git pull
```

**Comment by calvyb** [comment]
Sorted TY

**Comment by lolwulf2** [comment]
i am still fairly new to linux but this is what is inside the folder the path is also correct i but i could be wrong 
![Screenshot from 2024-10-16 04-43-28](https://github.com/user-attachments/assets/6731995c-d384-411e-99cf-f253ac6cf0fb)

and as you mentioned i am not using steam as a flatpack neither

**Comment by lolwulf2** [comment]
nvm fixed it had missed a step in the guide like an idiot

**Comment by marvin1099** [comment]
Sorry @lolwulf2 I seem to have missed that 2 people are in this issue, but it now works for you too that is good.

**Comment by lolwulf2** [comment]
yeah turned out i had missed a step in the guide lol. got so confused though when i saw the ticket had been closed
