### ISSUE TITLE
[BUG]: The WeMod launcher shows only a troubleshoot window

### ISSUE THREAD

**Issue by Dead-kiD** [DeckCheatz/wemod-launcher#134]
### Describe the bug

i followed the guide but i just getting a troubleshoot window.

### Steps to reproduce the behavior

Followed the full guide.

### Logs

[wemod.log](https://github.com/user-attachments/files/17519183/wemod.log)

### System Information

Steam os 3.6.19
GE-Proton 9-1

**Comment by Dead-kiD** [comment]
> It seams proton or the proton prefix is not working. Delete GE-Proton9.1 and the game prefix and redownload GE-Proton9.1 and retry. GE-Proton can be deleted using the progamm "proton-up" and the prefix can be deleted using the troubleshooter or check the full guide it also explaines how to delete game prefixes.

Tried deleting both and reinstalling proton, still the same

**Comment by marvin1099** [comment]
Delete the log file, try it and then send the new log file

**Comment by Dead-kiD** [comment]
[wemod.log](https://github.com/user-attachments/files/17605105/wemod.log)
here

**Comment by marvin1099** [comment]
It may be a bug of GE-Proton9-1
Try to download and use the newest GE-Proton9
Right now the newest version should be GE-Proton9-18

You can also try to run
```
WINEPREFIX=home/deck/.local/share/Steam/steamapps/compatdata/3269609047 winecfg
```
That should open a settings window close it and then also run
```
WINEPREFIX=home/deck/.local/share/Steam/steamapps/compatdata/3269609047 wine cmd
```

That way you should see if the wine prefix works in general (a black cmd window will open if it works).

See how far you can get with that.

**Comment by marvin1099** [comment]
I will close this for now, if you still have issues just ask.
