### ISSUE TITLE
[BUG]: The WeMod launcher crashes computer when pressing play

### ISSUE THREAD

**Issue by AssistantSnorlax** [DeckCheatz/wemod-launcher#135]
### Describe the bug

I managed to make everything work after install then i launched dying light and the wemod window popped up with a .net issue which i do not know how to fix and when clicking no on the error window game and wemod launch as normal?

Then i get into game from menu and click play on wemod menu

System then freezes and signs me out? 
when signing back in everything is gone (open applications)
However they still show up on task manager

Note: i have played the game prior to wemod installation and am at almost 90% story completion, so the game shouldnt be the issue

### Steps to reproduce the behavior

1. Install via full instructions
2. Launch dying light
3. click no on .net error
4. get into dying light game
5. press play on wemod
6. computer crashes

### Expected behavior

Computer Crash

### Logs

[wemod.log](https://github.com/user-attachments/files/17528779/wemod.log)

### System Information

Latest Endeavor OS with XFCE
1660 Super
 Latest GEProton 9-16

**Comment by marvin1099** [comment]
If you are using Wayland and a nvidea GPU,
this only works on some systems,
there is some issue that we can't fix (not part of this project).
If you use Wayland you can try to run steam with xwaxland that should give you a x11 window (its best to google / ask chat bots on how to run apps with x Wayland).
Or use X11 (also google or use some chat bot ;EG. huggingface.co/chat/ ; to learn how to do it. Would be realy complex if I explained it).

**Comment by marvin1099** [comment]
I will close this for now, if you still have issues just ask.
