### ISSUE TITLE
[BUG]: Constantly consumes memory until total steam crash.

### ISSUE THREAD

**Issue by Nythain** [DeckCheatz/wemod-launcher#136]
### Describe the bug

When I run a game without launcher, it will run and perform as usual. Using wemod-launcher, memory usage will increase beyond system specs and result in game and steam client crashing.

### Steps to reproduce the behavior

1. Launch game with with launch option /home/$USER/wemod-launcher/wemod %command%
2. Wait and watch memory consumption increase
3. Game and Steam client crash

### Expected behavior

Expected normal performance, with maybe a little more memory consumption but not 8+ gigs more.

### Logs

[wemod.log](https://github.com/user-attachments/files/17587518/wemod.log)

### System Information

OS: CachyOS
Proton Version: Proton-CachyOS

**Comment by Cacrawfordbsc** [comment]
I had this issue occur too, it looked like some kind of chrome process duplicating itself.

**Comment by Cacrawfordbsc** [comment]
CrRendererMain seems to be the culprit 
![Screenshot_20241031_144232](https://github.com/user-attachments/assets/95d7b3aa-39e0-45fe-b8ed-60ae0a72ff00)

**Comment by Nythain** [comment]
It's definitely the CrRendererMain that's doing it. Though they pop up almost as fast as i can kill them. Also, not exclusive to the launcher. I installed WeMod in it's own prefix in Lutris, and get the same results. Interestingly enough, it only happens once I click on a game, or go to add a game. Basically as soon as i do anything after launching it. Not sure how other people are using WeMod in linux, for me it's incredibly unstable. The apps UI will freeze as soon as the window loses focus, and there's almost no way to prevent this memory issue that I can find.

Thanks for your assistance. Gonna close this bug report.
