### ISSUE TITLE
[BUG]: The WeMod launcher won’t work for some games, shows odd message?

### ISSUE THREAD

**Issue by Monster-Collector** [DeckCheatz/wemod-launcher#142]
### Describe the problem

For 2 games so far, the following box is displayed on attempts to launch with the exact same process that works for all other games (proper command line added to launch options of game). For Monster Sanctuary and Dead Cells (so far), I get the Imput Wine Version box auto populated with WineGE8.26. Whether I hit OK or Cancel, run the game on Proton GE 8.26 or 9.20 (latest), nothing I do seems to work, be it downloading or building a prefix. Any ideas? Thank you!

### Steps that will result in the problem

1. Have /home/deck/wemod-launcher/wemod %command% in launch options of game
2. Choose Proton GE 8.26 / 9.20 for game to launch with in Compatibility 
3. Launch game
4. Be presented with the box shown in screenshot and regardless of options chosen be eventually met with the troubleshooter and no instance of the game itself launching![image](https://github.com/user-attachments/assets/4cab838d-b646-4448-90ac-a5447ab5e112)

### Expected results

I expected for it to download a build with 9.20 as my functioning games have and then proceed smoothly to wemod in one window and the game in another.

### Logs

Can’t access it right now

### Screenshots

![IMG_1535](https://github.com/user-attachments/assets/6beaac33-65ab-46d6-80de-6bb8531d12f0)

### System Information

SteamOS latest Stable (3.6.20)
Proton GE 8.26 / GE 9.20 / several others

**Comment by marvin1099** [comment]
Make sure the game runs without the wemod launcher first, 
the input wine version box only appears if the version file is missing 
(gets created with proton when the game runs),
So remove the launcher from the start options and start the game.
If it works close it and add the launcher launch options back.
Then just restart.

Also use the newest version of wine,
it usually runs better so use:
ProtonGE9.20
you can also try:
ProtonGE9.16 #this one worked in the past

The logs are located at /home/deck/wemod-launcher/wemod.log
If you followed the guide on the readme of the repo.
You can upload the log file on sites like https://file.io
If the file is not there you will need to go into desktop mode and run:
```
pkill steam
pkill steam-runtime
pkill steam-native
steam
```
in a teminal.
It should restart steam and any issues will then be printed into the opened console.

**Comment by Monster-Collector** [comment]
> Make sure the game runs without the wemod launcher first, 
> 
> the input wine version box only appears if the version file is missing 
> 
> (gets created with proton when the game runs),
> 
> So remove the launcher from the start options and start the game.
> 
> If it works close it and add the launcher launch options back.
> 
> Then just restart the game.
> 
> 
> 
> Also use the newest version of wine,
> 
> it usually runs better so use:
> 
> ProtonGE9.20
> 
> you can also try:
> 
> ProtonGE9.16 #this one worked in the past
> 
> 
> 
> The logs are located at /home/deck/wemod-launcher/wemod.log
> 
> If you followed the guide on the readme of the repo.
> 
> You can upload the log file on sites like https://file.io
> 
> If the file is not there you will need to go into desktop mode and run:
> 
> ```
> 
> pkill steam
> 
> pkill steam-runtime
> 
> pkill steam-native
> 
> steam
> 
> ```
> 
> in a teminal. 
> 
> This may not work as expected on the steam deck lets just hope we don't need that.
> 
> It should restart steam and any issues will then be printed into the opened console.

You legend, I'll give this a try as soon as I get home! Thank you for replying, I really appreciate your time bro
