### ISSUE TITLE
[BUG]: The WeMod launcher won`t install with either method

### ISSUE THREAD

**Issue by vanharen07** [DeckCheatz/wemod-launcher#143]
### Describe the problem

When doing the first run of the program it gives me one of two problems depending on the method used for installing. When using the "Download" option it exits with:"ERR:
name 'syncWeMod' is not defined"

and when using the "Build" option it exits with the attached image, and shows nothing in the logs.

The first part of the logs is using the download option and the second part the build option.

### Steps that will result in the problem

1. Follow the full install instructions as provided till step 5
2. Choose either the download option or the build option
3. Wait for the program to crash

### Expected results

The expected results were for the program to properly install

### Logs

The script wemod-launcher is running on version 1.506
Package 'FreeSimpleGUI' is missing
Externally managed environment detected.
Virtual environment created successfully.
Pip finished successfully
No updates available
Re-running script within virtual environment 
or to update or to run outside of flatpak with the command:
	['/home/ylva/wemod-launcher/wemod_venv/bin/python', '/home/ylva/wemod-launcher/wemod', '/home/ylva/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/home/ylva/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=49520', '--', '/home/ylva/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/ylva/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/proton', 'waitforexitandrun', '/home/ylva/.local/share/Steam/steamapps/common/Borderlands 2/Binaries/Win32/Launcher.exe']

The rerun nr 1 was started
The script wemod-launcher is running on version 1.506
No updates available
The normal args list is 12 long and the full contents are:
	['/home/ylva/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/home/ylva/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=49520', '--', '/home/ylva/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/ylva/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/proton', 'waitforexitandrun', '/home/ylva/.local/share/Steam/steamapps/common/Borderlands 2/Binaries/Win32/Launcher.exe']
Looking for init file '/home/ylva/.local/share/Steam/steamapps/compatdata/49520/pfx/.wemod_installer'
Looking for compatible wine prefixes in '/home/ylva/.local/share/Steam/steamapps/compatdata' with proton version '9.1'
No compatible Proton version found in the compatibility folder.
No versions to copy available
Looking once more for the init file
Init file not found! Attempting to prepare the WINEPREFIX
Using wine from Proton at path: '/home/ylva/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/files/bin'
RepoUser not set in config using: DeckCheatz
RepoName not set in config using: wemod-launcher
Cached file not found: '/home/ylva/wemod-launcher/.cache/wemod_prefix9.1.zip'
Unpacking prefix file /home/ylva/wemod-launcher/.cache/wemod_prefix9.1.zip into /home/ylva/.local/share/Steam/steamapps/compatdata/49520
ERR:
name 'syncWeMod' is not defined

--------------------------------------------------------------------------------

The script wemod-launcher is running on version 1.506
Package 'FreeSimpleGUI' is missing
Externally managed environment detected.
Virtual environment created successfully.
Pip finished successfully
No updates available
Re-running script within virtual environment 
or to update or to run outside of flatpak with the command:
	['/home/ylva/wemod-launcher/wemod_venv/bin/python', '/home/ylva/wemod-launcher/wemod', '/home/ylva/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/home/ylva/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=49520', '--', '/home/ylva/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/ylva/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/proton', 'waitforexitandrun', '/home/ylva/.local/share/Steam/steamapps/common/Borderlands 2/Binaries/Win32/Launcher.exe']

The rerun nr 1 was started
The script wemod-launcher is running on version 1.506
No updates available
The normal args list is 12 long and the full contents are:
	['/home/ylva/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/home/ylva/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=49520', '--', '/home/ylva/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/ylva/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/proton', 'waitforexitandrun', '/home/ylva/.local/share/Steam/steamapps/common/Borderlands 2/Binaries/Win32/Launcher.exe']
Looking for init file '/home/ylva/.local/share/Steam/steamapps/compatdata/49520/pfx/.wemod_installer'
Looking for compatible wine prefixes in '/home/ylva/.local/share/Steam/steamapps/compatdata' with proton version '9.1'
No compatible Proton version found in the compatibility folder.
No versions to copy available
Looking once more for the init file
Init file not found! Attempting to prepare the WINEPREFIX
Using wine from Proton at path: '/home/ylva/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/files/bin'
Dereferencing '/home/ylva/.local/share/Steam/steamapps/compatdata/49520/pfx/drive_c/windows'
Running dependencies installation. This could take a while...
Using winetricks 20240105-next - sha256sum: f1ee5af4e2e6daa5d3d72fe7ad2d18d500d311f8e8376f91e65206815e5c2f2e with wine-9.0 (Staging) and WINEARCH=win64
sourcehansans already installed, skipping
sourcehansans already installed, skipping
Downloading https://unifoundry.com/pub/unifont/unifont-13.0.06/font-builds/unifont-13.0.06.ttf to /home/ylva/.cache/winetricks/unifont

### Screenshots

![2024-12-08_17-28 35](https://github.com/user-attachments/assets/fa8b1fe3-3c41-451d-8764-1df5111669ad)

### System Information

OS: Artix Linux with kernel: 6.12.1-artix1-1
Proton version: Tried with proton-GE 9.20, 9.8 and 9.1 the logs are of 9.1
CPU: Ryzen 7 7800x3d
GPU: RX 7900 GRE
32GB ram

**Comment by marvin1099** [comment]
Sorry I seem to have made a typo, retry now it should work with downloading.

**Comment by vanharen07** [comment]
Works now. Thanks for the quick response
